In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('california_wildfires.csv')

In [3]:
df

                                                  Tweet  Label
0     RT @Gizmodo: Wildfires raging through Northern...      1
1     PHOTOS: Deadly wildfires rage in California ht...      1
2     RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...      1
3     RT @Cal_OES: PLS SHARE: Weâ€™re capturing wild...      1
4     RT @TIME: California's raging wildfires as you...      1
...                                                 ...    ...
1584  GOP targets environmental rules after Californ...      1
1585  Motorcycle crash sparked 350-acre fire in Clev...      1
1586  Carlâ€™s Jr. #SantaRosa catches #Fire while ma...      0
1587  Inside the List: The Romance Writer Who Almost...      1
1588  How long will heat, wildfire threat persist in...      0

[1589 rows x 2 columns]

In [4]:
df.isnull().sum()

Tweet    0
Label    0
dtype: int64

In [5]:
def lower(x):
    return x.lower()
df['Tweet']=df['Tweet'].apply(lower)

In [6]:
df

                                                  Tweet  Label
0     rt @gizmodo: wildfires raging through northern...      1
1     photos: deadly wildfires rage in california ht...      1
2     rt @cal_oes: pls share: weâ€™re capturing wild...      1
3     rt @cal_oes: pls share: weâ€™re capturing wild...      1
4     rt @time: california's raging wildfires as you...      1
...                                                 ...    ...
1584  gop targets environmental rules after californ...      1
1585  motorcycle crash sparked 350-acre fire in clev...      1
1586  carlâ€™s jr. #santarosa catches #fire while ma...      0
1587  inside the list: the romance writer who almost...      1
1588  how long will heat, wildfire threat persist in...      0

[1589 rows x 2 columns]

In [7]:
from emot.emo_unicode import UNICODE_EMOJI
# Function for converting emojis into word
def convert_emojis(text):
    for emot in UNICODE_EMOJI:
        text = text.replace(emot, "_".join(UNICODE_EMOJI[emot].replace(",","").replace(":","").split()))
    return text
df['Tweet']=df['Tweet'].apply(convert_emojis)

In [8]:
df

                                                  Tweet  Label
0     rt @gizmodo: wildfires raging through northern...      1
1     photos: deadly wildfires rage in california ht...      1
2     rt @cal_oes: pls share: weâ€trade_markre captu...      1
3     rt @cal_oes: pls share: weâ€trade_markre captu...      1
4     rt @time: california's raging wildfires as you...      1
...                                                 ...    ...
1584  gop targets environmental rules after californ...      1
1585  motorcycle crash sparked 350-acre fire in clev...      1
1586  carlâ€trade_marks jr. #santarosa catches #fire...      0
1587  inside the list: the romance writer who almost...      1
1588  how long will heat, wildfire threat persist in...      0

[1589 rows x 2 columns]

In [9]:
from nltk.tokenize import word_tokenize
def tokenize(x):
    return word_tokenize(x)
df['Tweet']=df['Tweet'].apply(tokenize)

In [10]:
df

                                                  Tweet  Label
0     [rt, @, gizmodo, :, wildfires, raging, through...      1
1     [photos, :, deadly, wildfires, rage, in, calif...      1
2     [rt, @, cal_oes, :, pls, share, :, weâ€trade_m...      1
3     [rt, @, cal_oes, :, pls, share, :, weâ€trade_m...      1
4     [rt, @, time, :, california, 's, raging, wildf...      1
...                                                 ...    ...
1584  [gop, targets, environmental, rules, after, ca...      1
1585  [motorcycle, crash, sparked, 350-acre, fire, i...      1
1586  [carlâ€trade_marks, jr., #, santarosa, catches...      0
1587  [inside, the, list, :, the, romance, writer, w...      1
1588  [how, long, will, heat, ,, wildfire, threat, p...      0

[1589 rows x 2 columns]

In [11]:
def remove_punct(x):
    import string
    punct_tag=set(string.punctuation)
    t=[i for i in x if i not in punct_tag]
    return t
      
df['Tweet']=df['Tweet'].apply(remove_punct)

In [12]:
df

                                                  Tweet  Label
0     [rt, gizmodo, wildfires, raging, through, nort...      1
1     [photos, deadly, wildfires, rage, in, californ...      1
2     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
3     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
4     [rt, time, california, 's, raging, wildfires, ...      1
...                                                 ...    ...
1584  [gop, targets, environmental, rules, after, ca...      1
1585  [motorcycle, crash, sparked, 350-acre, fire, i...      1
1586  [carlâ€trade_marks, jr., santarosa, catches, f...      0
1587  [inside, the, list, the, romance, writer, who,...      1
1588  [how, long, will, heat, wildfire, threat, pers...      0

[1589 rows x 2 columns]

In [13]:
def whites(x):
    w={' '}
    x=[i for i in x if i not in w]
    return x
df['Tweet']=df['Tweet'].apply(whites)

In [14]:
df

                                                  Tweet  Label
0     [rt, gizmodo, wildfires, raging, through, nort...      1
1     [photos, deadly, wildfires, rage, in, californ...      1
2     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
3     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
4     [rt, time, california, 's, raging, wildfires, ...      1
...                                                 ...    ...
1584  [gop, targets, environmental, rules, after, ca...      1
1585  [motorcycle, crash, sparked, 350-acre, fire, i...      1
1586  [carlâ€trade_marks, jr., santarosa, catches, f...      0
1587  [inside, the, list, the, romance, writer, who,...      1
1588  [how, long, will, heat, wildfire, threat, pers...      0

[1589 rows x 2 columns]

In [15]:
from nltk.corpus import stopwords
import nltk
def re_stop(x):
    nltk_stopwords = nltk.corpus.stopwords.words("english")
    return [ token for token in x if token not in nltk_stopwords]
df['Tweet']=df['Tweet'].apply(re_stop)

In [16]:
df

                                                  Tweet  Label
0     [rt, gizmodo, wildfires, raging, northern, cal...      1
1     [photos, deadly, wildfires, rage, california, ...      1
2     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
3     [rt, cal_oes, pls, share, weâ€trade_markre, ca...      1
4     [rt, time, california, 's, raging, wildfires, ...      1
...                                                 ...    ...
1584  [gop, targets, environmental, rules, californi...      1
1585  [motorcycle, crash, sparked, 350-acre, fire, c...      1
1586  [carlâ€trade_marks, jr., santarosa, catches, f...      0
1587  [inside, list, romance, writer, almost, lost, ...      1
1588  [long, heat, wildfire, threat, persist, califo...      0

[1589 rows x 2 columns]

In [17]:
from nltk.stem import WordNetLemmatizer
def lemm(x):
    l=[]
    for i in x:
        l.append(WordNetLemmatizer().lemmatize(i))
    return l    
df['Tweet']=df['Tweet'].apply(lemm)

In [18]:
from nltk.stem.porter import PorterStemmer
def stemm(x):
    l=[]
    for i in x:
        l.append(PorterStemmer().stem(i))
    return l    
df['Tweet']=df['Tweet'].apply(stemm)

In [19]:
def combine(x):
    return ' '.join(x)
df['Tweet']=df['Tweet'].apply(combine)

In [20]:
df

                                                  Tweet  Label
0     rt gizmodo wildfir rage northern california te...      1
1     photo deadli wildfir rage california http //t....      1
2     rt cal_o pl share weâ€trade_markr captur wildf...      1
3     rt cal_o pl share weâ€trade_markr captur wildf...      1
4     rt time california 's rage wildfir 've never s...      1
...                                                 ...    ...
1584  gop target environment rule california wildfir...      1
1585  motorcycl crash spark 350-acr fire cleveland n...      1
1586  carlâ€trade_mark jr. santarosa catch fire make...      0
1587  insid list romanc writer almost lost home cali...      1
1588  long heat wildfir threat persist california ht...      0

[1589 rows x 2 columns]

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X=tfidf.fit_transform(df['Tweet']).toarray()
#create bow
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer(max_features = 1500)
# X= cv.fit_transform(df['Tweet']).toarray()

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
global X_train, X_test, y_train, y_test 
X_train, X_test, y_train, y_test = train_test_split(X,df['Label'], test_size=0.2,random_state=35)

In [23]:
from sklearn.linear_model import LogisticRegression
model_l=LogisticRegression().fit(X_train,y_train)
y_pred=model_l.predict(X_test)
score=classification_report(y_test, y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        68
           1       0.79      1.00      0.88       250

    accuracy                           0.79       318
   macro avg       0.39      0.50      0.44       318
weighted avg       0.62      0.79      0.69       318

C:\Users\surya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\surya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\surya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [24]:
from sklearn.svm import SVC
rf_kn =SVC()
rf_model_kn = rf_kn.fit(X_train, y_train)
y_pred = rf_model_kn.predict(X_test)
score1=classification_report(y_test, y_pred)
print(score1)

              precision    recall  f1-score   support

           0       0.71      0.07      0.13        68
           1       0.80      0.99      0.88       250

    accuracy                           0.80       318
   macro avg       0.76      0.53      0.51       318
weighted avg       0.78      0.80      0.72       318

In [25]:
from sklearn.tree import DecisionTreeClassifier
rf_kn = DecisionTreeClassifier()
rf_model_kn = rf_kn.fit(X_train, y_train)
y_pred = rf_model_kn.predict(X_test)
score1=classification_report(y_test, y_pred)
print(score1)

              precision    recall  f1-score   support

           0       0.29      0.13      0.18        68
           1       0.79      0.91      0.85       250

    accuracy                           0.75       318
   macro avg       0.54      0.52      0.52       318
weighted avg       0.69      0.75      0.71       318

In [26]:
from sklearn.ensemble import RandomForestClassifier
rf_kn = RandomForestClassifier()
rf_model_kn = rf_kn.fit(X_train, y_train)
y_pred = rf_model_kn.predict(X_test)
score1=classification_report(y_test, y_pred)
print(score1)

              precision    recall  f1-score   support

           0       0.71      0.07      0.13        68
           1       0.80      0.99      0.88       250

    accuracy                           0.80       318
   macro avg       0.76      0.53      0.51       318
weighted avg       0.78      0.80      0.72       318

In [27]:
from sklearn.neighbors import KNeighborsClassifier
rf_kn = KNeighborsClassifier()
rf_model_kn = rf_kn.fit(X_train, y_train)
y_pred = rf_model_kn.predict(X_test)
score1=classification_report(y_test, y_pred)
print(score1)

              precision    recall  f1-score   support

           0       0.43      0.15      0.22        68
           1       0.80      0.95      0.87       250

    accuracy                           0.78       318
   macro avg       0.62      0.55      0.54       318
weighted avg       0.72      0.78      0.73       318

In [28]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
score1=classification_report(y_test, y_pred)
print(score1)

              precision    recall  f1-score   support

           0       0.27      0.37      0.31        68
           1       0.81      0.72      0.76       250

    accuracy                           0.65       318
   macro avg       0.54      0.55      0.54       318
weighted avg       0.69      0.65      0.67       318

In [29]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(objective="binary:logistic", random_state=42)
xgb_model.fit(X_train, y_train)
y_pred=xgb_model.predict(X_test)
score1=classification_report(y_test,y_pred.round())
print(score1)

              precision    recall  f1-score   support

           0       0.55      0.26      0.36        68
           1       0.82      0.94      0.88       250

    accuracy                           0.80       318
   macro avg       0.69      0.60      0.62       318
weighted avg       0.76      0.80      0.77       318

In [30]:
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import StackingClassifier

estimator_list = [
        ("knn", KNeighborsClassifier()),
        ("svm_rbf", SVC()),
        ("dt", DecisionTreeClassifier()),
        ("rf", RandomForestClassifier()),
        ("mlp", MLPClassifier(alpha=1, max_iter=1000)),
    ]
stack_model = StackingClassifier(
        estimators=estimator_list, final_estimator=LogisticRegression()
    )
stack_model.fit(X_train, y_train)
y_pred = stack_model.predict(X_test)
score = classification_report(y_test, y_pred)
print(score)

              precision    recall  f1-score   support

           0       0.50      0.13      0.21        68
           1       0.80      0.96      0.88       250

    accuracy                           0.79       318
   macro avg       0.65      0.55      0.54       318
weighted avg       0.74      0.79      0.73       318

In [36]:
# nltk
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk import FreqDist

# Preprocessing
import re
import string
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import pandas as pd
import numpy as np
import os

# Modeling
from sklearn.model_selection import KFold, cross_val_score, GridSearchCV 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
#from imblearn.over_sampling import SMOTE
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, plot_confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import classification_report
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [39]:
def voting():
    global vcl
    if vcl == "V_RANDOM_CL":
        score = v_RandomForest_classifier()
    elif vcl == "V_DECISION_CL":
        score = v_decision_tree_classifier()
    elif vcl == "V_KNN_CL":
        score = v_KNeighbors_classifier()
    elif vcl == "V_SVC_CL":
        score = v_SVC_classsifier()
    elif vcl == "V_all":
        score = v_all()
    return score


def v_RandomForest_classifier():
    models = list()
    models.append(("dt1", RandomForestClassifier(max_depth=2)))
    models.append(("dt3", RandomForestClassifier(max_depth=3)))
    models.append(("dt5", RandomForestClassifier(max_depth=4)))
    models.append(("dt7", RandomForestClassifier(max_depth=5)))
    models.append(("dt9", RandomForestClassifier(max_depth=6)))
    ensemble = VotingClassifier(estimators=models, voting="soft")
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    score = classification_report(y_test, y_pred)
    return score


def v_decision_tree_classifier():
    models = list()
    models.append(("dt1", DecisionTreeClassifier(max_depth=2)))
    models.append(("dt3", DecisionTreeClassifier(max_depth=3)))
    models.append(("dt5", DecisionTreeClassifier(max_depth=4)))
    models.append(("dt7", DecisionTreeClassifier(max_depth=5)))
    models.append(("dt9", DecisionTreeClassifier(max_depth=6)))
    ensemble = VotingClassifier(estimators=models, voting="soft")
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    score = classification_report(y_test, y_pred)
    return score


def v_KNeighbors_classifier():
    models = list()
    models.append(("knn1", KNeighborsClassifier(n_neighbors=1)))
    models.append(("knn3", KNeighborsClassifier(n_neighbors=3)))
    models.append(("knn5", KNeighborsClassifier(n_neighbors=5)))
    models.append(("knn7", KNeighborsClassifier(n_neighbors=7)))
    models.append(("knn9", KNeighborsClassifier(n_neighbors=9)))
    ensemble = VotingClassifier(estimators=models, voting="soft")
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    score = classification_report(y_test, y_pred)
    return score


def v_SVC_classsifier():
    models = list()
    models.append(("svm1", SVC(probability=True, kernel="poly", degree=1)))
    models.append(("svm2", SVC(probability=True, kernel="poly", degree=2)))
    models.append(("svm3", SVC(probability=True, kernel="poly", degree=3)))
    models.append(("svm4", SVC(probability=True, kernel="poly", degree=4)))
    models.append(("svm5", SVC(probability=True, kernel="poly", degree=5)))
    ensemble = VotingClassifier(estimators=models, voting="soft")
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    score = classification_report(y_test, y_pred)
    return score


def v_all():
    models = [
        ("knn", KNeighborsClassifier()),
        ("svm_rbf", SVC(probability=True)),
        ("dt", DecisionTreeClassifier()),
        ("rf", RandomForestClassifier()),
        ("mlp", MLPClassifier(alpha=1, max_iter=1000)),
    ]
    ensemble = VotingClassifier(estimators=models, voting="soft")
    ensemble.fit(X_train, y_train)
    y_pred = ensemble.predict(X_test)
    score = classification_report(y_test, y_pred)
    return score

In [44]:
score=v_SVC_classsifier()
# score

In [45]:
print(score)

{'0': {'precision': 0.7142857142857143, 'recall': 0.07352941176470588, 'f1-score': 0.13333333333333333, 'support': 68}, '1': {'precision': 0.797427652733119, 'recall': 0.992, 'f1-score': 0.8841354723707665, 'support': 250}, 'accuracy': 0.7955974842767296, 'macro avg': {'precision': 0.7558566835094167, 'recall': 0.5327647058823529, 'f1-score': 0.50873440285205, 'support': 318}, 'weighted avg': {'precision': 0.7796488734424789, 'recall': 0.7955974842767296, 'f1-score': 0.7235865872935795, 'support': 318}}